// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH8WjaG9RMzutqpEV86y5Fjz0PPd6mr-M',
    appId: '1:493250041764:web:a709e1bfee0e4303129331',
    messagingSenderId: '493250041764',
    projectId: 'habitu-84a74',
    authDomain: 'habitu-84a74.firebaseapp.com',
    storageBucket: 'habitu-84a74.firebasestorage.app',
    measurementId: 'G-S3K4MHNPV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFUhhLleeVv5anMvQMNCHcVadJH0Ypd1U',
    appId: '1:493250041764:android:99f4c5e4414a0892129331',
    messagingSenderId: '493250041764',
    projectId: 'habitu-84a74',
    storageBucket: 'habitu-84a74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2AQOgMqy22fHD8aONlyoIgJWJmH2uQF0',
    appId: '1:493250041764:ios:bf69f9ce586a8825129331',
    messagingSenderId: '493250041764',
    projectId: 'habitu-84a74',
    storageBucket: 'habitu-84a74.firebasestorage.app',
    iosBundleId: 'com.example.habitu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2AQOgMqy22fHD8aONlyoIgJWJmH2uQF0',
    appId: '1:493250041764:ios:bf69f9ce586a8825129331',
    messagingSenderId: '493250041764',
    projectId: 'habitu-84a74',
    storageBucket: 'habitu-84a74.firebasestorage.app',
    iosBundleId: 'com.example.habitu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH8WjaG9RMzutqpEV86y5Fjz0PPd6mr-M',
    appId: '1:493250041764:web:48915c6899301ffa129331',
    messagingSenderId: '493250041764',
    projectId: 'habitu-84a74',
    authDomain: 'habitu-84a74.firebaseapp.com',
    storageBucket: 'habitu-84a74.firebasestorage.app',
    measurementId: 'G-KSDTEW24P5',
  );
}
